### ISSUE TITLE
Configurable Environment Variables

### ISSUE THREAD

**Issue by karolkieglerski** [cscetbon/casskop#106]
## Feature Request

We as need ability to add custom Environment Variable to each Cassandra container. It can be added by a list of key: value. 

example solution in `values.yaml`:
```yaml
env_vars:
   casandra:
       VERSION: 3.11
       CUSTOM_FLAG: test_value
```
