### ISSUE TITLE
Embeded Prometheus exporter doesn't work with cassandra:4.1.4

### ISSUE THREAD

**Issue by Subetov** [cscetbon/casskop#140]
## Bug Report

**What did you do?**

 -   deployed casskop:2.2.2
 -  deployed multi-casskop:2.2.2
 -  created multi-casskop resource

```
apiVersion: db.orange.com/v2
kind: MultiCasskop
metadata:
  name: test
  namespace: ice-cassandra
spec:
  base:
    apiVersion: db.orange.com/v2
    kind: CassandraCluster
    metadata:
      creationTimestamp: null
      labels:
        cluster: test
      name: test
      namespace: test-cassandra
    spec:
      autoPilot: true
      backRestSidecar:
        image: ghcr.io/cscetbon/instaclustr-icarus:2.0.4
        imagePullPolicy: IfNotPresent
      bootstrapImage: ghcr.io/cscetbon/casskop-bootstrap:0.1.14
      cassandraImage: cassandra:4.1.4
      configBuilderImage: datastax/cass-config-builder:1.0.8
      # configMapName: cassandra-configmap
      dataCapacity: 10Gi
      imagePullSecret:
        name: ice-cassandra-image-pull-artifactory
      imagepullpolicy: IfNotPresent
      maxPodUnavailable: 1
      noCheckStsAreEqual: true
      nodesPerRacks: 1
      resources:
        limits:
          cpu: "4"
          memory: 12Gi
        requests:
          cpu: "2"
          memory: 4Gi
      runAsUser: 999
    status:
      seedlist:
      - test-dc1-rack1-0.ice.ice-cassandra.svc.cluster.local
  deleteCassandraCluster: true
  override:
    dc1:
      spec:
        topology:
          dc:
          - name: dc1
            rack:
            - name: rack1
```

**What did you expect to see?**
No "[prometheus-netty-pool-0] java.lang.NoSuchMethodError" exception

**What did you see instead? Under which circumstances?**
```
cassandra WARN  [prometheus-netty-pool-0] 2024-03-29 11:17:35,064 DefaultChannelPipeline.java:1152 - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
cassandra java.lang.NoSuchMethodError: 'java.net.InetAddress org.apache.cassandra.utils.FBUtilities.getBroadcastAddress()'
cassandra     at com.zegelin.cassandra.exporter.InternalMetadataFactory.localBroadcastAddress(InternalMetadataFactory.java:87)
cassandra     at com.zegelin.cassandra.exporter.Harvester.globalLabels(Harvester.java:280)
cassandra     at com.zegelin.cassandra.exporter.netty.HttpHandler.sendMetrics(HttpHandler.java:289)
cassandra     at com.zegelin.cassandra.exporter.netty.HttpHandler.channelRead0(HttpHandler.java:91)
cassandra     at com.zegelin.cassandra.exporter.netty.HttpHandler.channelRead0(HttpHandler.java:36)
cassandra     at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
cassandra     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
cassandra     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
cassandra     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
cassandra     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
cassandra     at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
cassandra     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
cassandra     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
cassandra     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
cassandra     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
cassandra     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
cassandra     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
cassandra     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
cassandra     at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
cassandra     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
cassandra     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
cassandra     at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
cassandra     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
cassandra     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
cassandra     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
cassandra     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
cassandra     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
cassandra     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
cassandra     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
cassandra     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
cassandra     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
cassandra     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
cassandra     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
cassandra     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
cassandra     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
cassandra     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
cassandra     at java.base/java.lang.Thread.run(Unknown Source)
```

**Environment**
* casskop version: v2.2.2

* go version:

* Kubernetes version information: v1.29.2

* Kubernetes cluster kind: k3s v1.29.2

* Cassandra version: 4.1.4
